//! User-created theme persistence (`themes.json` in the app data dir),
//! mirroring `crate::settings`'s load/save shape. `themes.json` stores only
//! user-created themes; the built-in palettes are synthesized by
//! [`built_in_themes`] and never written to disk, so they can't drift out
//! of sync with themselves and can't be deleted or overwritten by id
//! collision.

use std::fs;
use std::path::{Path, PathBuf};

use rand::RngCore;

use crate::error::{AppError, AppResult};
use crate::models::{Theme, ThemeColors, ThemeInput};

/// Reserved id for the default (dark) built-in palette - never generated by
/// [`new_id`] (which produces 32 hex characters), never persisted in
/// `themes.json`.
pub const ROSE_DEFAULT_THEME_ID: &str = "rose-default";
/// Reserved id for the light built-in palette - same guarantees as
/// [`ROSE_DEFAULT_THEME_ID`].
pub const ROSE_LIGHT_THEME_ID: &str = "rose-light";
pub const DRACULA_THEME_ID: &str = "dracula";
pub const NORD_THEME_ID: &str = "nord";
pub const CATPPUCCIN_THEME_ID: &str = "catppuccin";
pub const GRUVBOX_THEME_ID: &str = "gruvbox";

/// Every reserved built-in id, in one place so `is_built_in_id` and
/// [`built_in_themes`] can't drift out of sync with each other.
const BUILT_IN_THEME_IDS: [&str; 6] = [
    ROSE_DEFAULT_THEME_ID,
    ROSE_LIGHT_THEME_ID,
    DRACULA_THEME_ID,
    NORD_THEME_ID,
    CATPPUCCIN_THEME_ID,
    GRUVBOX_THEME_ID,
];

const THEMES_FILENAME: &str = "themes.json";

/// Mirrors `global.css`'s `:root` block exactly - if one changes, the other
/// must too. `destructive` is given a plain hex approximation of the
/// stylesheet's `oklch(0.577 0.245 27.325)` here, since it needs to be
/// editable through an `<input type="color">`, which only speaks hex.
fn rose_default_colors() -> ThemeColors {
    ThemeColors {
        background: "#0b1822".to_string(),
        foreground: "#e8edf2".to_string(),
        card: "#10202c".to_string(),
        card_foreground: "#e8edf2".to_string(),
        popover: "#10202c".to_string(),
        popover_foreground: "#e8edf2".to_string(),
        primary: "#eb9020".to_string(),
        primary_foreground: "#0b1822".to_string(),
        secondary: "#16283a".to_string(),
        secondary_foreground: "#e8edf2".to_string(),
        muted: "#16283a".to_string(),
        muted_foreground: "#9cabb9".to_string(),
        accent: "#1d3244".to_string(),
        accent_foreground: "#e8edf2".to_string(),
        destructive: "#e7000b".to_string(),
        border: "#334459".to_string(),
        input: "#334459".to_string(),
        ring: "#eb9020".to_string(),
        nav_foreground: "#9cabb9".to_string(),
        avatar_background: "#16283a".to_string(),
        avatar_foreground: "#9cabb9".to_string(),
    }
}

/// A light counterpart to `rose_default_colors` - same brand `primary`/
/// `ring` gold and `destructive` red, everything else inverted to a light
/// surface hierarchy (white cards on an off-white background, dark text).
/// Not derived from the dark palette by a formula (e.g. inverting
/// lightness) - each value is chosen directly, since a mechanical inversion
/// of a hand-tuned dark theme doesn't reliably produce a good light one.
fn rose_light_colors() -> ThemeColors {
    ThemeColors {
        background: "#f5f6f8".to_string(),
        foreground: "#101820".to_string(),
        card: "#ffffff".to_string(),
        card_foreground: "#101820".to_string(),
        popover: "#ffffff".to_string(),
        popover_foreground: "#101820".to_string(),
        primary: "#eb9020".to_string(),
        primary_foreground: "#1a1206".to_string(),
        secondary: "#eef0f3".to_string(),
        secondary_foreground: "#101820".to_string(),
        muted: "#eef0f3".to_string(),
        muted_foreground: "#5b6672".to_string(),
        accent: "#e7ecf1".to_string(),
        accent_foreground: "#101820".to_string(),
        destructive: "#e7000b".to_string(),
        border: "#dde2e7".to_string(),
        input: "#dde2e7".to_string(),
        ring: "#eb9020".to_string(),
        nav_foreground: "#5b6672".to_string(),
        avatar_background: "#eef0f3".to_string(),
        avatar_foreground: "#5b6672".to_string(),
    }
}

/// Community favorites, added on request ("look up the most popular theme
/// choices"). Confirmed via live research at the time this was written
/// (Catppuccin, Tokyo Night, Gruvbox, Nord, and Dracula turned up as the
/// consistent top-5 across current terminal/editor theme rankings) - these
/// four were picked for name recognition, with exact hex values pulled from
/// each project's own official palette/source rather than approximated:
/// Dracula (draculatheme.com/contribute), Nord (nordtheme.com/docs/colors-
/// and-palettes), Catppuccin Mocha (catppuccin.com/palette), Gruvbox dark
/// (github.com/morhetz/gruvbox's colors/gruvbox.vim).
///
/// None of these projects define a full UI color system (card/popover/
/// secondary/muted/accent/border) - only a core syntax-highlighting
/// palette - so those roles are filled in using the same mapping approach
/// for all four: the theme's own "elevated surface" tone for card/popover/
/// secondary/muted/accent/border, its most iconic accent color for
/// primary/ring, its red for destructive, and its comment/subtext tone for
/// muted-foreground. Same methodology `rose_light_colors` used to extend
/// `rose_default_colors`'s brand colors into a full palette.
fn dracula_colors() -> ThemeColors {
    ThemeColors {
        background: "#282a36".to_string(),
        foreground: "#f8f8f2".to_string(),
        card: "#21222c".to_string(),
        card_foreground: "#f8f8f2".to_string(),
        popover: "#21222c".to_string(),
        popover_foreground: "#f8f8f2".to_string(),
        primary: "#bd93f9".to_string(),
        primary_foreground: "#282a36".to_string(),
        secondary: "#44475a".to_string(),
        secondary_foreground: "#f8f8f2".to_string(),
        muted: "#44475a".to_string(),
        muted_foreground: "#6272a4".to_string(),
        accent: "#44475a".to_string(),
        accent_foreground: "#f8f8f2".to_string(),
        destructive: "#ff5555".to_string(),
        border: "#44475a".to_string(),
        input: "#44475a".to_string(),
        ring: "#bd93f9".to_string(),
        nav_foreground: "#6272a4".to_string(),
        avatar_background: "#44475a".to_string(),
        avatar_foreground: "#6272a4".to_string(),
    }
}

/// Nord's own docs assign nord3 to "comments" and nord4 to primary text -
/// taken literally, that made regular text merely readable and muted text
/// (used far more widely in this app's UI - timestamps, descriptions - than
/// a code comment ever is) nearly illegible: nord3 `#4c566a` sits too close
/// in lightness to the nord1/nord2 surfaces it renders on. Shifted the
/// whole text tier up one step (foreground -> nord6, the brightest snow-
/// storm shade; muted-foreground -> nord4, the shade `foreground` used to
/// use) so both stay clearly legible while muted text is still visibly
/// de-emphasized relative to full foreground. nord3 stays reserved for
/// `border`/`input`, where low contrast is the intended, subtle look.
fn nord_colors() -> ThemeColors {
    ThemeColors {
        background: "#2e3440".to_string(),
        foreground: "#eceff4".to_string(),
        card: "#3b4252".to_string(),
        card_foreground: "#eceff4".to_string(),
        popover: "#3b4252".to_string(),
        popover_foreground: "#eceff4".to_string(),
        primary: "#88c0d0".to_string(),
        primary_foreground: "#2e3440".to_string(),
        secondary: "#434c5e".to_string(),
        secondary_foreground: "#eceff4".to_string(),
        muted: "#434c5e".to_string(),
        muted_foreground: "#d8dee9".to_string(),
        accent: "#434c5e".to_string(),
        accent_foreground: "#eceff4".to_string(),
        destructive: "#bf616a".to_string(),
        border: "#4c566a".to_string(),
        input: "#4c566a".to_string(),
        ring: "#88c0d0".to_string(),
        nav_foreground: "#d8dee9".to_string(),
        avatar_background: "#434c5e".to_string(),
        avatar_foreground: "#d8dee9".to_string(),
    }
}

/// `primary`/`ring` use Peach, not Mauve - Mauve sits in the same
/// purple-navy hue family as the background/surface colors, so a Mauve
/// button reads as barely distinct from its surroundings ("lacks pastel
/// pop," reported after seeing it applied). Peach is warm against a cool
/// base, giving the accent actual hue contrast to pop against rather than
/// just being a slightly lighter shade of the same color.
fn catppuccin_colors() -> ThemeColors {
    ThemeColors {
        background: "#1e1e2e".to_string(),
        foreground: "#cdd6f4".to_string(),
        card: "#313244".to_string(),
        card_foreground: "#cdd6f4".to_string(),
        popover: "#181825".to_string(),
        popover_foreground: "#cdd6f4".to_string(),
        primary: "#fab387".to_string(),
        primary_foreground: "#1e1e2e".to_string(),
        secondary: "#313244".to_string(),
        secondary_foreground: "#cdd6f4".to_string(),
        muted: "#313244".to_string(),
        muted_foreground: "#a6adc8".to_string(),
        accent: "#45475a".to_string(),
        accent_foreground: "#cdd6f4".to_string(),
        destructive: "#f38ba8".to_string(),
        border: "#45475a".to_string(),
        input: "#45475a".to_string(),
        ring: "#fab387".to_string(),
        nav_foreground: "#a6adc8".to_string(),
        avatar_background: "#313244".to_string(),
        avatar_foreground: "#a6adc8".to_string(),
    }
}

fn gruvbox_colors() -> ThemeColors {
    ThemeColors {
        background: "#282828".to_string(),
        foreground: "#ebdbb2".to_string(),
        card: "#3c3836".to_string(),
        card_foreground: "#ebdbb2".to_string(),
        popover: "#3c3836".to_string(),
        popover_foreground: "#ebdbb2".to_string(),
        primary: "#fe8019".to_string(),
        primary_foreground: "#282828".to_string(),
        secondary: "#504945".to_string(),
        secondary_foreground: "#ebdbb2".to_string(),
        muted: "#504945".to_string(),
        muted_foreground: "#a89984".to_string(),
        accent: "#504945".to_string(),
        accent_foreground: "#ebdbb2".to_string(),
        destructive: "#fb4934".to_string(),
        border: "#665c54".to_string(),
        input: "#665c54".to_string(),
        ring: "#fe8019".to_string(),
        nav_foreground: "#a89984".to_string(),
        avatar_background: "#504945".to_string(),
        avatar_foreground: "#a89984".to_string(),
    }
}

/// Every built-in palette, in display order. A `Vec` (not a fixed-size
/// array) so `list`/`get` can extend/search it the same way they do the
/// saved library - adding another built-in later is a one-line change here
/// rather than touching every call site.
fn built_in_themes() -> Vec<Theme> {
    vec![
        Theme {
            id: ROSE_DEFAULT_THEME_ID.to_string(),
            name: "Dark Theme".to_string(),
            colors: rose_default_colors(),
            built_in: true,
        },
        Theme {
            id: ROSE_LIGHT_THEME_ID.to_string(),
            name: "Light Theme".to_string(),
            colors: rose_light_colors(),
            built_in: true,
        },
        Theme {
            id: DRACULA_THEME_ID.to_string(),
            name: "Dracula".to_string(),
            colors: dracula_colors(),
            built_in: true,
        },
        Theme {
            id: NORD_THEME_ID.to_string(),
            name: "Nord".to_string(),
            colors: nord_colors(),
            built_in: true,
        },
        Theme {
            id: CATPPUCCIN_THEME_ID.to_string(),
            name: "Catppuccin".to_string(),
            colors: catppuccin_colors(),
            built_in: true,
        },
        Theme {
            id: GRUVBOX_THEME_ID.to_string(),
            name: "Gruvbox".to_string(),
            colors: gruvbox_colors(),
            built_in: true,
        },
    ]
}

fn is_built_in_id(id: &str) -> bool {
    BUILT_IN_THEME_IDS.contains(&id)
}

fn themes_file_path(app_data_dir: &Path) -> PathBuf {
    app_data_dir.join(THEMES_FILENAME)
}

/// User-created themes only (never includes a built-in). Missing file
/// (first run, or an app data dir that predates this feature) is not an
/// error - just an empty library, matching `settings::load`'s
/// create-on-first-access spirit without needing to eagerly write a file
/// for the common case of "no custom themes yet."
fn load_saved(app_data_dir: &Path) -> AppResult<Vec<Theme>> {
    let path = themes_file_path(app_data_dir);
    if !path.exists() {
        return Ok(Vec::new());
    }
    let contents = fs::read_to_string(&path)?;
    let themes: Vec<Theme> = serde_json::from_str(&contents)?;
    Ok(themes)
}

fn save_all(app_data_dir: &Path, themes: &[Theme]) -> AppResult<()> {
    fs::create_dir_all(app_data_dir)?;
    let contents = serde_json::to_string_pretty(themes)?;
    fs::write(themes_file_path(app_data_dir), contents)?;
    Ok(())
}

/// Both built-in palettes, prepended, followed by every saved custom theme.
pub fn list(app_data_dir: &Path) -> AppResult<Vec<Theme>> {
    let mut all = built_in_themes();
    all.extend(load_saved(app_data_dir)?);
    Ok(all)
}

/// Built-in or a saved theme by id - used by export, which needs a
/// `ThemeColors` regardless of which kind of theme was picked.
pub fn get(app_data_dir: &Path, id: &str) -> AppResult<Theme> {
    if let Some(built_in) = built_in_themes().into_iter().find(|t| t.id == id) {
        return Ok(built_in);
    }
    load_saved(app_data_dir)?
        .into_iter()
        .find(|t| t.id == id)
        .ok_or(AppError::ThemeNotFound)
}

/// Creates a new theme (`input.id: None`) or updates an existing one in
/// place (`input.id: Some(id)`, matched by id - if no saved theme has that
/// id, it's added rather than erroring, so an id round-tripped from a
/// previous `theme_save` response always works). Rejects touching a
/// built-in id - the UI never exposes editing one (see `Theme.built_in`),
/// this is defense-in-depth only.
pub fn upsert(app_data_dir: &Path, input: ThemeInput) -> AppResult<Theme> {
    if input.id.as_deref().is_some_and(is_built_in_id) {
        return Err(AppError::Internal(
            "cannot modify a built-in theme".to_string(),
        ));
    }

    let mut saved = load_saved(app_data_dir)?;
    let theme = Theme {
        id: input.id.unwrap_or_else(new_id),
        name: input.name,
        colors: input.colors,
        built_in: false,
    };

    if let Some(existing) = saved.iter_mut().find(|t| t.id == theme.id) {
        *existing = theme.clone();
    } else {
        saved.push(theme.clone());
    }
    save_all(app_data_dir, &saved)?;
    Ok(theme)
}

/// Errors [`AppError::ThemeNotFound`] if `id` isn't a saved theme, or
/// rejects a built-in id outright (same defense-in-depth as `upsert`).
/// Does not touch `settings.toml` - if the deleted theme was active, that's
/// the caller's responsibility (`commands::theme::theme_delete`), since
/// this module has no reason to know about settings.
pub fn delete(app_data_dir: &Path, id: &str) -> AppResult<()> {
    if is_built_in_id(id) {
        return Err(AppError::Internal(
            "cannot delete a built-in theme".to_string(),
        ));
    }

    let mut saved = load_saved(app_data_dir)?;
    let before = saved.len();
    saved.retain(|t| t.id != id);
    if saved.len() == before {
        return Err(AppError::ThemeNotFound);
    }
    save_all(app_data_dir, &saved)
}

/// 16 random bytes, hex-encoded - not a `uuid` crate dependency, since
/// `rand`/`data-encoding` are already dependencies (see `crypto/mod.rs` for
/// the same `thread_rng().fill_bytes()` pattern). Timestamp-based ids were
/// considered and rejected: Windows' ~15.6ms default timer resolution makes
/// collisions plausible across rapid create/duplicate/import flows.
fn new_id() -> String {
    let mut bytes = [0u8; 16];
    rand::thread_rng().fill_bytes(&mut bytes);
    data_encoding::HEXLOWER.encode(&bytes)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_colors() -> ThemeColors {
        rose_default_colors()
    }

    /// A fresh, uniquely-named directory under the OS temp dir - avoids
    /// adding a `tempfile` dev-dependency just for these tests, matching
    /// this module's own "reuse what's already a dependency" approach to
    /// `new_id`. Not cleaned up afterward (OS temp dir, negligible size,
    /// matches this codebase having no existing temp-dir test precedent to
    /// follow either way).
    struct TempDir(PathBuf);

    impl TempDir {
        fn new() -> Self {
            let mut suffix = [0u8; 8];
            rand::thread_rng().fill_bytes(&mut suffix);
            let dir = std::env::temp_dir().join(format!(
                "rose-theme-test-{}",
                data_encoding::HEXLOWER.encode(&suffix)
            ));
            fs::create_dir_all(&dir).unwrap();
            TempDir(dir)
        }

        fn path(&self) -> &Path {
            &self.0
        }
    }

    #[test]
    fn list_always_includes_every_built_in_first_and_only_them() {
        let dir = TempDir::new();
        let themes = list(dir.path()).unwrap();
        assert_eq!(themes.len(), BUILT_IN_THEME_IDS.len());
        for (theme, expected_id) in themes.iter().zip(BUILT_IN_THEME_IDS.iter()) {
            assert_eq!(&theme.id, expected_id);
            assert!(theme.built_in);
        }
    }

    #[test]
    fn upsert_with_no_id_creates_and_generates_an_id_not_colliding_with_a_built_in() {
        let dir = TempDir::new();
        let theme = upsert(
            dir.path(),
            ThemeInput {
                id: None,
                name: "My Theme".to_string(),
                colors: sample_colors(),
            },
        )
        .unwrap();

        assert!(!is_built_in_id(&theme.id));
        assert!(!theme.built_in);
        assert_eq!(list(dir.path()).unwrap().len(), BUILT_IN_THEME_IDS.len() + 1);
    }

    #[test]
    fn upsert_with_existing_id_updates_in_place() {
        let dir = TempDir::new();
        let created = upsert(
            dir.path(),
            ThemeInput {
                id: None,
                name: "Original".to_string(),
                colors: sample_colors(),
            },
        )
        .unwrap();

        let updated = upsert(
            dir.path(),
            ThemeInput {
                id: Some(created.id.clone()),
                name: "Renamed".to_string(),
                colors: sample_colors(),
            },
        )
        .unwrap();

        assert_eq!(updated.id, created.id);
        let all = list(dir.path()).unwrap();
        assert_eq!(all.len(), BUILT_IN_THEME_IDS.len() + 1);
        assert_eq!(all.last().unwrap().name, "Renamed");
    }

    #[test]
    fn upsert_rejects_every_built_in_id() {
        let dir = TempDir::new();
        for id in BUILT_IN_THEME_IDS {
            let result = upsert(
                dir.path(),
                ThemeInput {
                    id: Some(id.to_string()),
                    name: "Hijacked".to_string(),
                    colors: sample_colors(),
                },
            );
            assert!(result.is_err(), "expected upsert({id}) to be rejected");
        }
    }

    #[test]
    fn delete_removes_a_saved_theme() {
        let dir = TempDir::new();
        let created = upsert(
            dir.path(),
            ThemeInput {
                id: None,
                name: "Temp".to_string(),
                colors: sample_colors(),
            },
        )
        .unwrap();

        delete(dir.path(), &created.id).unwrap();
        assert_eq!(list(dir.path()).unwrap().len(), BUILT_IN_THEME_IDS.len());
    }

    #[test]
    fn delete_errors_on_unknown_id() {
        let dir = TempDir::new();
        let result = delete(dir.path(), "does-not-exist");
        assert!(matches!(result, Err(AppError::ThemeNotFound)));
    }

    #[test]
    fn delete_rejects_every_built_in_id() {
        let dir = TempDir::new();
        for id in BUILT_IN_THEME_IDS {
            let result = delete(dir.path(), id);
            assert!(result.is_err(), "expected delete({id}) to be rejected");
        }
    }

    #[test]
    fn get_returns_every_built_in_without_touching_disk() {
        let dir = TempDir::new();
        for id in BUILT_IN_THEME_IDS {
            assert!(get(dir.path(), id).unwrap().built_in, "expected get({id}) to be built-in");
        }
    }
}
